'use client'
//import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import Container from 'react-bootstrap/Container';
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify';
// import '@/components/app.footer.tsx';
// import '@/components/app.header.tsx';
// import '@/components/app.table.tsx';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader></AppHeader>
        <Container style={{ minHeight: 'calc(100vh-106px)' }}>
          {children}
        </Container>
        <AppFooter></AppFooter>
        <ToastContainer
          position="top-right"
          autoClose={1000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>


    </html>
  )
}
