'use client'
//import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import Container from 'react-bootstrap/Container';
// import '@/components/app.footer.tsx';
// import '@/components/app.header.tsx';
// import '@/components/app.table.tsx';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader></AppHeader>
        <Container>
          {children}
        </Container>
        <AppFooter></AppFooter>
      </body>


    </html>
  )
}
